### ISSUE TITLE
Clarify differences

### ISSUE THREAD

**Issue by carstenblt** [akyriako/typesense-helm#1]
Hey,
thank you for your work!

I would really appreciate if you could showcase the difference to the other implementation https://github.com/Spittal/typesense-helm
And maybe also some hints if this is considered production ready.

Thank you!

**Comment by akyriako** [comment]
Hi @carstenblt, thank you for taking an interest in this helm chart. I jump straight to answer your questions:

1. https://github.com/Spittal/typesense-helm is **not** fit for purpose as from a quick look I had, it utilizes a `Deployment` to provision typesense, and `Deployments` by nature are not meant for stateful applications, as they cannot form a cluster; each `Pod` will act indiviually as a stateless entity. You need to use a `StatefulSet`, as this helm chart here does.
2. Is this Helm Chart production ready? Yes it is, but with a big asterisk that derives from intricancies of the underlying raft protocol. It is production ready **until** it gets a "flat tire" and then creates a bunch of problems. I discovered it on the way, as I use it for production workloads myself! For that matter, I am working on another project which is 95% ready and is on the final test phase, that eliminates all the problems that typesense, by design, faces within Kubernetes. The project will be finalized till mid-December and then I will permanently discontinue this Helm Chart. You can find an extensive analysis of the raft issues and how they are solved in an extensive analysis under the new project: https://github.com/akyriako/typesense-operator
